behaviors:
  Snake:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 10000

# training with curriculum --> https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-ML-Agents.md#curriculum
environment_parameters:
  max_snake_body_count:
    curriculum:
      - name: Lesson_1 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Snake
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.99 # if grid is 5x5 --> (25 - snake head) = 24
          require_reset: true
        value: 2.0 # train with max 2 snake body parts
      - name: Lesson_2
        completion_criteria:
          measure: reward
          behavior: Snake
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.99
          require_reset: true
        value: 5.0 # train with max 5 snake body parts --> TODO --> Change this to a uniform sampler!!
      - name: Lesson_3
        completion_criteria:
          measure: reward
          behavior: Snake
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.99
          require_reset: true
        value: # train with max these snake body parts:
          sampler_type: uniform
          sampler_parameters:
            min_value: 5.0
            max_value: 10.0
      - name: Lesson_4
        completion_criteria:
          measure: reward
          behavior: Snake
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.99
          require_reset: true
        value: # train with max these snake body parts:
          sampler_type: uniform
          sampler_parameters:
            min_value: 10.0
            max_value: 20.0
      - name: Lesson_Final
        value: 24.0 # train with max 24 snake body parts
  # maybe add another environment parameter that takes in the grid size

  # TODO --> I should change the WonGame() method to have a higher reward!!! - and it should clear the snake body parts
  #      --> OR!! --> Change the rewards system so that the episode only ends if it wins the game?